### ISSUE TITLE
Why LSTM dataset's input and output size are 104 and 96 but other DNN datasets' input and output are 104 and 104 ?

### ISSUE THREAD

**Issue by yaoniao** [abdulkarimgizzini/Temporal-Averaging-LSTM-based-Channel-Estimation-Scheme-for-IEEE-802.11p-Standard#1]

**Comment by abdulkarimgizzini** [comment]
Hello @yaoniao, Thank you for your interest in my research.
This is because, in DNN, the input and output vectors include 48 data subcarriers  + 4 pilots =  52 subcarriers (complex) = 104 (real). However, in the LSTM estimator, we only care about the 48 data sub-carriers at the output (output vector size = 96 real), where the additional 4 pilots are inserted into the output vector to form a new 104 input vector. 
Please let me know if you have any more questions.

**Comment by yaoniao** [comment]
Thank you very much! I am new to the field of channel estimation and have great interest in your research. Thanks to your research, I have got a lot from that. And if I have other questions in the nearly future, could I send e-mails to you?

**Comment by abdulkarimgizzini** [comment]
@yaoniao Yes sure, contact me on abdulkarimgizzini@gmail.com
We can schedule an online meeting to discuss further issues if needed.
